{
 "title": "Host Overview",
 "tags": [
  "hosts",
  "prometheus",
  "node-exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "job",
    "label": "Job:",
    "query": "label_values(node_boot_time_seconds, job)"
   },
   {
    "name": "port",
    "label": "Port:",
    "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "stat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "stat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Free Filesystem Space (Lowest)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$node:$port\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node:$port*\"})"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'} ",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes{instance=~\"$node:$port\"}[24h]))"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes{instance=~\"$node:$port\"}[24h]))"
    }
   ]
  },
  {
   "title": "Ram Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\"} - node_memory_Cached_bytes{instance=~\"$node:$port\"} - node_memory_Buffers_bytes{instance=~\"$node:$port\"} - node_memory_Slab_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\"} + node_memory_Slab_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "RAM Used %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (sum by (instance) (node_memory_MemFree_bytes{instance=~\"$node:$port\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\"} + node_memory_Cached_bytes{instance=~\"$node:$port\"})) / (sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$node:$port\"})) ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:$port\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:$port\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{instance=~\"$node:$port\", mode!=\"idle\"}[5m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$node:$port\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "sum(node_load5{instance=~\"$node:$port\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "sum(node_load15{instance=~\"$node:$port\"})",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "cpu busy %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node:$port\"}[1m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device=~\"/dev/.*\"} - node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device=~\"/dev/.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space available, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(min by (mountpoint) (node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device=~\"/dev/.*\",}/node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device=~\"/dev/.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Use per Filesystem",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{instance=~\"$node:$port\",fstype=~\"xfs|ext4\"} / node_filesystem_size_bytes{instance=~\"$node:$port\",fstype=~\"xfs|ext4\"} * 100)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}